version: '2'
services:
  app:
    restart: always
    image: a2c-app
    container_name: a2c-app
    depends_on:
       - postgres
    links:
      - postgres:postgres
    volumes:
      - ./angular2cloud:/code
      - a2c-static:/www/static
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /www/media:/www/media
    networks:
      - back
    env_file: .env
    environment:
      - ALLOWED_HOST=angular2cloud.com
      - MEDIA_ROOT=/www/media
      - DEBUG=false
    expose:
      - "8000"
    command: bash initialize.sh



  nginx:
    restart: always
    image: a2c-nginx-app
    container_name: a2c-nginx-app
    volumes:
      - /var/www/html:/usr/share/nginx/html
    volumes_from:
      - app:ro
    links:
      - app:app
    environment:
      - VIRTUAL_HOST=angular2cloud.com,www.angular2cloud.com
      - LETSENCRYPT_EMAIL=cloudangular@gmail.com
      - LETSENCRYPT_HOST=angular2cloud.com,www.angular2cloud.com
    networks:
      - reverse-proxy
      - back

  postgres:
    restart: always
    image: postgres
    container_name: a2c-postgres
    env_file: .env
    expose:
      - "5432"
    volumes:
      - a2c-pgdata:/var/lib/postgresql/data/
    networks:
      - back


volumes:
    a2c-pgdata:
        external: true
    a2c-static:
        external: true


networks:
  reverse-proxy:
    external:
      name: reverse-proxy
  back:
    driver: bridge